version: '3.3'

services:

  # Initial cluster member
  neo4j_db:
    build: ./neo4j-db
    image: neo4j-db:latest
    volumes:
      - ./neo4j-db:C:/neo4j-db
      - ./config:C:/config
    #entrypoint: "powershell C:/neo4j/docker-entrypoint.ps1"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
      - "1337:1337"


  data_collector:
    build: ./data-collector
    image: data-collector:latest
    entrypoint: c:\\nodejs\\node.exe c:\\data-collector\\dataingestor.js
    #entrypoint: ping -t localhost
    hostname: bloodhound02
    ports:
      - "8080:8080"
    depends_on:
      - "neo4j_db"
    volumes:
      - ".\\data-collector:C:\\data-collector"
      - ".\\config:C:\\config"
    security_opt:
      - credentialspec=file://bluehound_bloodhound02.json
    dns:
      - "192.168.43.2"
      - "8.8.8.8"
    user: "NT AUTHORITY\\SYSTEM"
    networks:
      - default
      - domain

  jupyter_bloodhound:
    build: ./jupyter-bloodhound
    image: jupyter-bloodhound:latest
    ports:
      - "8888:8888"
    volumes:
      - ".\\config:C:\\config"
    restart: always

networks:
  domain:
    external:
      name: "BHNet"